#!/bin/bash

echo "installing homebrew..."
which brew >/dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "run brew doctor..."
which brew >/dev/null 2>&1 && brew doctor

echo "run brew update..."
which brew >/dev/null 2>&1 && brew update

echo "ok. run brew upgrade..."
brew upgrade

apps=(
  gh
  git
  mysql
  tmux
  tmuxinator
  tree
  warp
  yarn
  mas
  go
  zsh-completions
  zsh-autosuggestions
  zsh-git-prompt

  deepl
  docker
  dropbox
  iterm2
  notion
  obs
  shottr
  slack
  visual-studio-code
  corsor
  clipy
  rectangle
  rubymine
  raycast
)

echo "brew tap"
# brew tap thirdparty
brew tap homebrew/cask-fonts

echo "brew install apps"
for app in "${apps[@]}"; do
  brew install $app || brew upgrade $app
done

# stores=(
# )

# echo "app stores"
# for store in "${stores[@]}"; do
#   mas install $store
# done

brew cleanup

echo "brew installed"
