name: test
on: 
  pull_request:
    branches:
      - main
jobs:
  test:
      name: Test
      runs-on: macos-latest
      steps:
        - name: Install chezmoi
          run: brew install chezmoi
        - name: Initialize chezmoi
          run: chezmoi init https://github.com/ko-tominaga/dotfiles.git
        - name: Apply chezmoi
          run: chezmoi apply
